# Generated by Django 4.2.5 on 2024-12-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_Dias', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_Horas', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=12)),
                ('rut', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Barberia.dias')),
                ('hora_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Barberia.horas')),
                ('usuario_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Barberia.usuario')),
            ],
        ),
    ]
