# Generated by Django 4.1.13 on 2025-09-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barberia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=20)),
            ],
        ),
    ]
