# Generated by Django 4.1.13 on 2025-09-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Barberia', '0002_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='Tipo_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Barberia.tipo_servicio'),
            preserve_default=False,
        ),
    ]
