# Generated by Django 4.1.13 on 2025-09-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barberia', '0003_horario_tipo_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_servicio',
            old_name='tipo_servicio',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='tipo_servicio',
            name='precio_servicio',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
