# Generated by Django 4.1.13 on 2025-11-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barberia', '0004_rename_tipo_servicio_tipo_servicio_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Atendida'), ('C', 'Cancelada')], default='p', max_length=1),
        ),
    ]
