# Generated by Django 4.1.13 on 2025-11-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barberia', '0005_horario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Atendida'), ('C', 'Cancelada')], default='P', max_length=1),
        ),
    ]
