# Generated by Django 4.1.13 on 2025-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barberia', '0006_alter_horario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
