# Generated by Django 4.1.13 on 2025-12-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barberia', '0007_horario_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaCerrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
