# Generated by Django 4.1.13 on 2025-12-12 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barberia', '0008_diacerrado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diacerrado',
            options={'verbose_name': 'Día Cerrado', 'verbose_name_plural': 'Días Cerrados'},
        ),
        migrations.AddField(
            model_name='diacerrado',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 1, 1), unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diacerrado',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
