# Generated by Django 4.2.23 on 2025-12-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barberia', '0009_alter_diacerrado_options_diacerrado_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='agregados',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'ADDON'}, related_name='horarios_agregados', to='Barberia.tipo_servicio'),
        ),
        migrations.AddField(
            model_name='tipo_servicio',
            name='tipo',
            field=models.CharField(choices=[('BASE', 'Base'), ('ADDON', 'Agregado')], default='BASE', max_length=10),
        ),
        migrations.AlterField(
            model_name='tipo_servicio',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
